#!/bin/bash
# Wrapper around poster commands

function usage {
  echo "Usage: $0 [-h] [-s A3] [-m poster|pdfposter] infile.pdf outfile.pdf";
  echo ""
  echo "Converts an a4 PDF into a set of tiles that can be assembled into a"
  echo "larger poster."
  echo ""
  echo "Options:"
  echo "  -s a3|a2|a1|a0      Set final size, once all a4 tiles have been assembled."
  echo "                      Default: a3"
  echo "  -m poster|pdfposter Set internal method for conversion."
  echo "                      Default: poster"
  echo ""
  exit $1;
}
other_args=();
DEST_SIZE='2x1A4'
METHOD=poster
# an option followed by : means "takes an argument", set in $OPTARG
while getopts "hm:s:" opt; do
  case $opt in
    h )   usage 0 ;;
    s )   case "$OPTARG" in
          a3 ) DEST_SIZE='2x1A4';;
          a2 ) DEST_SIZE='2x2A4';;
          a1 ) DEST_SIZE='4x2A4';;
          a0 ) DEST_SIZE='4x4A4';;
          * ) echo "Sorry, I only understand a3, a2, a1 or a0 sizes." >&2
            usage 1
        esac;;
    m )   case "$OPTARG" in
          poster ) METHOD=$OPTARG;;
          pdfposter ) METHOD=$OPTARG;;
          * ) echo "Method must be poster or pdfposter" >&2
            usage 1;;
        esac;;
    \? )  usage 1 ;;
  esac
done
shift $((OPTIND-1))
INFILE="$1"
OUTFILE="$2"
[ -e "$INFILE" ] || { echo "Missing or unreadable input filename" >&2; usage 1; }
[ -e "$OUTFILE" ] || { echo "Missing or unreadable output filename" >&2; usage 1; }

case "$METHOD" in
  poster )
    REQUIRED_MISSING=''
    which pdftops >/dev/null || REQUIRED_MISSING="poppler-utils $REQUIRED_MISSING"
    which poster >/dev/null || REQUIRED_MISSING="poster $REQUIRED_MISSING"
    which ps2pdf >/dev/null || REQUIRED_MISSING="ghostscript $REQUIRED_MISSING"
    if [ -n "$REQUIRED_MISSING" ]
    then
      echo "Missing required packages: $REQUIRED_MISSING" >&2
      exit 1
    fi
    pdftops -eps "$INFILE" - | poster -p2x1A4  | ps2pdf - "$OUTFILE" 
    ;;

  pdfposter )
    REQUIRED_MISSING=''
    if ! which pdfposter >/dev/null
    then
      echo "Missing required packages: $REQUIRED_MISSING" >&2
      exit 1
    fi
    pdfposter -p$DEST_SIZE "$INFILE" "$OUTFILE"
    ;;
esac

